name: ecommerce_bloc_1
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.5
  provider: ^6.0.3
  flutter_bloc: ^8.0.1
  shared_preferences: ^2.0.15
  material_design_icons_flutter: ^5.0.6595
  google_fonts: ^3.0.1
  flutter_spinkit: ^5.1.0
  cached_network_image: ^3.2.1
  intl: ^0.17.0
  connectivity_plus: ^2.3.5
  http: ^0.13.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/